-- 기준 스키마.
--
-- 이 파일은 엔티티에서 뽑아낸 것이다(jakarta.persistence.schema-generation).
-- 손으로 쓴 것이 아니므로 컬럼 순서가 알파벳이 아니라 타입별로 묶여 있다.
--
-- ddl-auto 가 validate 라, 여기서 만든 스키마와 엔티티가 어긋나면 앱이 뜨지
-- 않는다. 엔티티를 고치면 반드시 새 V 파일을 같이 써야 한다.
--
-- 두 DB 에서 그대로 돌아가야 해서 다음을 지켰다.
--   * generated by default as identity  — H2 / PostgreSQL 10+ 공통
--   * timestamp(6) with time zone       — PostgreSQL 에서는 timestamptz 가 된다
--   * TEXT                              — 양쪽 모두 긴 문자열 타입
--   * source_type 은 varchar + check    — H2 의 enum(...) 문법은 PostgreSQL 이
--                                         받지 않는다. 엔티티에도 JdbcTypeCode 로
--                                         못박아 두었다.
-- 제약 이름은 Hibernate 가 만든 해시 대신 읽을 수 있는 이름으로 바꿨다.
-- validate 는 제약 이름을 보지 않는다.

create table composer (
    id        bigint generated by default as identity,
    name      varchar(255) not null,
    name_en   varchar(255),
    slug      varchar(255) not null unique,
    born_year integer,
    died_year integer,
    bio       TEXT,
    primary key (id)
);

create table work (
    id             bigint generated by default as identity,
    composer_id    bigint not null,
    title          varchar(255) not null,
    title_original varchar(255),
    catalog        varchar(255),
    year_composed  integer,
    slug           varchar(255) not null unique,
    summary        varchar(500),
    story          TEXT,
    published      boolean not null,
    created_at     timestamp(6) with time zone not null,
    updated_at     timestamp(6) with time zone,
    primary key (id)
);

create table recording (
    id               bigint generated by default as identity,
    work_id          bigint not null,
    source_type      varchar(20) not null check (source_type in ('YOUTUBE', 'SELF_HOSTED')),
    youtube_id       varchar(20),
    audio_url        varchar(255),
    performer        varchar(255),
    license          varchar(255),
    source_url       varchar(255),
    attribution      varchar(255),
    start_offset     integer,
    end_offset       integer,
    duration_seconds integer,
    is_default       boolean not null,
    available        boolean not null,
    created_at       timestamp(6) with time zone not null,
    primary key (id)
);

alter table work
    add constraint fk_work_composer
    foreign key (composer_id) references composer;

alter table recording
    add constraint fk_recording_work
    foreign key (work_id) references work;

-- 자주 거는 조회. 목록은 published 로 거르고 연도순으로 정렬하며,
-- 상세는 slug 로 찾는다(slug 는 unique 제약이 이미 색인을 만든다).
create index idx_work_published_year on work (published, year_composed);
create index idx_work_composer on work (composer_id);
create index idx_recording_work on recording (work_id);
